version: '3'

services:
  postgres:
    image: postgres:16-alpine
    container_name: hbt-finances
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
